/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTurmasRouteImport } from './routes/_app.turmas'
import { Route as AppSubstituicoesRouteImport } from './routes/_app.substituicoes'
import { Route as AppSalasRouteImport } from './routes/_app.salas'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProfessoresRouteImport } from './routes/_app.professores'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasRoute = AppTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AppRoute,
} as any)
const AppSubstituicoesRoute = AppSubstituicoesRouteImport.update({
  id: '/substituicoes',
  path: '/substituicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppSalasRoute = AppSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessoresRoute = AppProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/professores': typeof AppProfessoresRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/salas': typeof AppSalasRoute
  '/substituicoes': typeof AppSubstituicoesRoute
  '/turmas': typeof AppTurmasRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/professores': typeof AppProfessoresRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/salas': typeof AppSalasRoute
  '/substituicoes': typeof AppSubstituicoesRoute
  '/turmas': typeof AppTurmasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/professores': typeof AppProfessoresRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/salas': typeof AppSalasRoute
  '/_app/substituicoes': typeof AppSubstituicoesRoute
  '/_app/turmas': typeof AppTurmasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/configuracoes'
    | '/professores'
    | '/relatorios'
    | '/salas'
    | '/substituicoes'
    | '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/configuracoes'
    | '/professores'
    | '/relatorios'
    | '/salas'
    | '/substituicoes'
    | '/turmas'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/cadastro'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/professores'
    | '/_app/relatorios'
    | '/_app/salas'
    | '/_app/substituicoes'
    | '/_app/turmas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/turmas': {
      id: '/_app/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AppTurmasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/substituicoes': {
      id: '/_app/substituicoes'
      path: '/substituicoes'
      fullPath: '/substituicoes'
      preLoaderRoute: typeof AppSubstituicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salas': {
      id: '/_app/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof AppSalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/professores': {
      id: '/_app/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof AppProfessoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppProfessoresRoute: typeof AppProfessoresRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSalasRoute: typeof AppSalasRoute
  AppSubstituicoesRoute: typeof AppSubstituicoesRoute
  AppTurmasRoute: typeof AppTurmasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppProfessoresRoute: AppProfessoresRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSalasRoute: AppSalasRoute,
  AppSubstituicoesRoute: AppSubstituicoesRoute,
  AppTurmasRoute: AppTurmasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
